- become: yes
  hosts: all
  name: obs-install
  tasks:
      - name: Add obs studio repository
        ansible.builtin.apt_repository:
            repo: ppa:obsproject/obs-studio
            state: present
      - name: Apt get update
        apt:
            update_cache: yes
      - name: Install ffmpeg
        apt:
            name: ffmpeg
            state: latest
      - name: Install obs-studio
        apt:
            name: obs-studio 
            state: latest
      - name: Install xrdp
        apt:
            name: xrdp 
            state: latest
      - name: Install xfce4
        apt:
            name: xfce4
            state: latest
      - name: Install xfce4-goodies
        apt:
            name: xfce4-goodies
            state: latest
      - name: Set xsession
        lineinfile:
            path: /home/bleed/.xsession
            line: xfce4-session
            create: yes
      - name: Add the user bleed and add it to sudo
        user:
            name: bleed
            group: sudo
            uid: 1001
            createhome: yes
            home: /home/bleed

