- become: yes
  hosts: all
  name: obs-install
  vars_files:
    - external_vars.yml
  tasks:
      - name: Wait for /var/lib/dpkg/lock-frontend to be released 
        shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;
      - name: Wait for /var/lib/apt/lists/lock to be released 
        shell: while lsof /var/lib/apt/lists/lock ; do sleep 10; done;
      - name: Add obs studio repository
        ansible.builtin.apt_repository:
            repo: ppa:obsproject/obs-studio
            state: present
      - name: Apt get update
        apt:
            update_cache: yes
      - name: Install ffmpeg
        apt:
            name: ffmpeg
            state: latest
      - name: Install obs-studio
        apt:
            name: obs-studio 
            state: latest
      - name: Install xrdp
        apt:
            name: xrdp 
            state: latest
      - name: Install xfce4
        apt:
            name: xfce4
            state: latest
      - name: Install xfce4-goodies
        apt:
            name: xfce4-goodies
            state: latest
      - name: Add the user bleed and add it to sudo
        user:
            name: bleed
            group: sudo
            uid: 1001
            createhome: yes
            home: /home/bleed
            password: "{{ password | password_hash('sha512') }}"
      - name: Set xsession
        lineinfile:
            path: /home/bleed/.xsession
            line: startxfce4
            owner: bleed
            create: yes
      # - name: Install obs scene
      #   copy:
      #     src: STR_Fest.json
      #     dest: /home/bleed/.config/obs-studio/basic/scenes
      #     owner: bleed
      #     group: sudo
